#ifndef RR_MBEDTLS_CONFIG_H
#define RR_MBEDTLS_CONFIG_H
#define MBEDTLS_AES_C
#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_GCM_C
#define MBEDTLS_MD_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_HKDF_C
#define MBEDTLS_NO_PLATFORM_ENTROPY
#undef MBEDTLS_AES_ALT
#undef MBEDTLS_CIPHER_C
#undef MBEDTLS_PLATFORM_C
#undef MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE
#endif
